# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2534dd3ac42f64b223ff4ff1ebff89835ee3796bd1cd11453085b3d6fd1046fe0a8e5a406c6c423e477c1ece9d447497e643031658ed3ec40152716ac2dabfa5

test:
  secret_key_base: 3241bd243e823f1fdd4399cab95c263193598ac735292014787d97bfbafa145a62efa5beeed21c6980bc1355f3754295dee96209d8020c21e6bea9114411dbb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
